PROG := coserviced

SRCS :=	codiscover.c \
	coprovide.c \
	coservice_cap.c \
	coservice_table.c \
	coserviced.c \
	coserviced_setup.c

DEP_LIBS := pthread comsg ccmalloc coproc cocall


include $(MK_DIR)/comesg.prog.mk

