PROG := coserviced

SRCS :=	codiscover.c \
	codiscover2.c \
	coprovide.c \
	coprovide2.c \
	coservice_cap.c \
	coservice_table.c \
	coserviced.c \
	coserviced_setup.c

DEP_LIBS := pthread comsg cocall


include $(MK_DIR)/comsg.prog.mk

