PROG := nsd

SRCS :=	cocreate.c \
	codelete.c \
	codrop.c \
	coinsert.c \
	coselect.c \
	coupdate.c \
	namespace_table.c \
	nsd.c \
	nsd_cap.c \
	nsd_crud.c \
	nsd_lookup.c \
	nsd_setup.c 

DEP_LIBS := pthread comsg cocall

include $(MK_DIR)/comsg.prog.mk

