PROG := coserviced

SRCS :=	cocreate.c \
	codelete.c \
	codrop.c \
	coinsert.c \
	coselect.c \
	coupdate.c \
	namespace_table.c \
	nsd.c \
	nsd_crud.c \
	nsd_lookup.c \
	nsd_setup.c 

include $(COMSG_DIR)/comsg.prog.mk

